In [1]:
import numpy as np
from findiff import FinDiff
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
def f(x,y):
    return 5*x**2 - 5*x + 10*y**2 -10*y

def act_df_dx(x, y):
    return 10*x-5

def act_df_dy(x, y):
    return 20*y-10

In [3]:
x = np.linspace(-10,0, 11).reshape((-1,1))
y = np.linspace(0,10,11).reshape((-1,1))
x

array([[-10.],
       [ -9.],
       [ -8.],
       [ -7.],
       [ -6.],
       [ -5.],
       [ -4.],
       [ -3.],
       [ -2.],
       [ -1.],
       [  0.]])

In [4]:
y

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [5]:
f_x_y = f(x,y)
print(f_x_y)

[[550.]
 [450.]
 [380.]
 [340.]
 [330.]
 [350.]
 [400.]
 [480.]
 [590.]
 [730.]
 [900.]]


In [6]:
df_dx = act_df_dx(x,y)
df_dx

array([[-105.],
       [ -95.],
       [ -85.],
       [ -75.],
       [ -65.],
       [ -55.],
       [ -45.],
       [ -35.],
       [ -25.],
       [ -15.],
       [  -5.]])

In [7]:
df_dy = act_df_dy(x,y)
df_dy

array([[-10.],
       [ 10.],
       [ 30.],
       [ 50.],
       [ 70.],
       [ 90.],
       [110.],
       [130.],
       [150.],
       [170.],
       [190.]])

In [10]:
diff_length = .1
d_dx = FinDiff(0,diff_length)
d_dy = FinDiff(1,diff_length)

In [12]:
points = np.array(list(zip(x,y)))

In [17]:
findiff_df_dx = d_dx(f(points))

TypeError: f() missing 1 required positional argument: 'y'

In [18]:
findiff_df_dx

array([[-1150.],
       [ -850.],
       [ -550.],
       [ -250.],
       [   50.],
       [  350.],
       [  650.],
       [  950.],
       [ 1250.],
       [ 1550.],
       [ 1850.]])

In [14]:
diff = .01
x = np.linspace(-10,0,11)
y = np.linspace(0,10,11)

X, Y = np.meshgrid(x, y, indexing='ij')

d_dx = FinDiff(0, diff)

df_dx = d_dx(f(X, Y))

In [15]:
df_dx

array([[-10500., -10500., -10500., -10500., -10500., -10500., -10500.,
        -10500., -10500., -10500., -10500.],
       [ -9500.,  -9500.,  -9500.,  -9500.,  -9500.,  -9500.,  -9500.,
         -9500.,  -9500.,  -9500.,  -9500.],
       [ -8500.,  -8500.,  -8500.,  -8500.,  -8500.,  -8500.,  -8500.,
         -8500.,  -8500.,  -8500.,  -8500.],
       [ -7500.,  -7500.,  -7500.,  -7500.,  -7500.,  -7500.,  -7500.,
         -7500.,  -7500.,  -7500.,  -7500.],
       [ -6500.,  -6500.,  -6500.,  -6500.,  -6500.,  -6500.,  -6500.,
         -6500.,  -6500.,  -6500.,  -6500.],
       [ -5500.,  -5500.,  -5500.,  -5500.,  -5500.,  -5500.,  -5500.,
         -5500.,  -5500.,  -5500.,  -5500.],
       [ -4500.,  -4500.,  -4500.,  -4500.,  -4500.,  -4500.,  -4500.,
         -4500.,  -4500.,  -4500.,  -4500.],
       [ -3500.,  -3500.,  -3500.,  -3500.,  -3500.,  -3500.,  -3500.,
         -3500.,  -3500.,  -3500.,  -3500.],
       [ -2500.,  -2500.,  -2500.,  -2500.,  -2500.,  -2500.,  -2500.,
 

In [20]:
df_0_0_dx = d_dx(f((0,0)))

TypeError: f() missing 1 required positional argument: 'y'