In [1]:
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.getcwd())))
import numpy as np
from findiff import FinDiff
import matplotlib.pyplot as plt
import pandas as pd
from pressure_drop import piping_pressure_drop
%matplotlib inline
%load_ext autoreload
%autoreload

In [2]:
def f(x,y):
    return 5*x**2 - 5*x + 10*y**2 -10*y

def act_df_dx(x, y):
    return 10*x-5

def act_df_dy(x, y):
    return 20*y-10

In [3]:
piping_pressure_drop.finite_partial(f,.01, 0,2, [0,0])

[-0.01  0.    0.01]
[array([-0.01,  0.  ,  0.01]), array([0., 0., 0.])]
[-5.1 -5.  -4.9]


C:\ProgramData\Anaconda3\lib\site-packages\findiff\findiff.py:242: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  yd[ref_multi_slice] += w * y[off_multi_slice]


-5.0

In [4]:
x = np.linspace(-10,0, 11).reshape((-1,1))
y = np.linspace(0,10,11).reshape((-1,1))
x

array([[-10.],
       [ -9.],
       [ -8.],
       [ -7.],
       [ -6.],
       [ -5.],
       [ -4.],
       [ -3.],
       [ -2.],
       [ -1.],
       [  0.]])

In [5]:
y

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [6]:
f_x_y = f(x,y)
print(f_x_y)

[[550.]
 [450.]
 [380.]
 [340.]
 [330.]
 [350.]
 [400.]
 [480.]
 [590.]
 [730.]
 [900.]]


In [7]:
df_dx = act_df_dx(x,y)
df_dx

array([[-105.],
       [ -95.],
       [ -85.],
       [ -75.],
       [ -65.],
       [ -55.],
       [ -45.],
       [ -35.],
       [ -25.],
       [ -15.],
       [  -5.]])

In [8]:
df_dy = act_df_dy(x,y)
df_dy

array([[-10.],
       [ 10.],
       [ 30.],
       [ 50.],
       [ 70.],
       [ 90.],
       [110.],
       [130.],
       [150.],
       [170.],
       [190.]])

In [24]:
diff_length = .1  # Findiff uses the grid spacing doesn't reevaluate around points using this
d_dx = FinDiff(0,x[1]-x[0])
d_dy = FinDiff(1,y[1]-y[0])
y_1 = np.zeros(len(x))+1
points = [x,y_1]

In [25]:
findiff_df_dx = d_dx(f(*points))

In [26]:
findiff_df_dx

array([-105.,  -95.,  -85.,  -75.,  -65.,  -55.,  -45.,  -35.,  -25.,
        -15.,   -5.])

In [18]:
diff = .01
x = np.linspace(-10,0,11)
y = np.linspace(0,10,11)

X, Y = np.meshgrid(x, y, indexing='ij')

d_dx = FinDiff(0, x[1]-x[0])

df_dx = d_dx(f(X, Y))

In [19]:
df_dx

array([[-105., -105., -105., -105., -105., -105., -105., -105., -105.,
        -105., -105.],
       [ -95.,  -95.,  -95.,  -95.,  -95.,  -95.,  -95.,  -95.,  -95.,
         -95.,  -95.],
       [ -85.,  -85.,  -85.,  -85.,  -85.,  -85.,  -85.,  -85.,  -85.,
         -85.,  -85.],
       [ -75.,  -75.,  -75.,  -75.,  -75.,  -75.,  -75.,  -75.,  -75.,
         -75.,  -75.],
       [ -65.,  -65.,  -65.,  -65.,  -65.,  -65.,  -65.,  -65.,  -65.,
         -65.,  -65.],
       [ -55.,  -55.,  -55.,  -55.,  -55.,  -55.,  -55.,  -55.,  -55.,
         -55.,  -55.],
       [ -45.,  -45.,  -45.,  -45.,  -45.,  -45.,  -45.,  -45.,  -45.,
         -45.,  -45.],
       [ -35.,  -35.,  -35.,  -35.,  -35.,  -35.,  -35.,  -35.,  -35.,
         -35.,  -35.],
       [ -25.,  -25.,  -25.,  -25.,  -25.,  -25.,  -25.,  -25.,  -25.,
         -25.,  -25.],
       [ -15.,  -15.,  -15.,  -15.,  -15.,  -15.,  -15.,  -15.,  -15.,
         -15.,  -15.],
       [  -5.,   -5.,   -5.,   -5.,   -5.,   -5.,   -5.,   -

In [20]:
df_0_0_dx = d_dx(f((0,0)))

TypeError: f() missing 1 required positional argument: 'y'

In [23]:
dt = .01
t = 1
a = np.arange(t-3*dt, t+3*dt, dt )
a

array([0.97, 0.98, 0.99, 1.  , 1.01, 1.02, 1.03])